<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitySeeder extends Seeder
{
    public function run(): void
    {
        $en_nationalities = [
            "Afghan",
            "Albanian",
            "Algerian",
            "American",
            "Andorran",
            "Angolan",
            "Antiguans",
            "Argentinean",
            "Armenian",
            "Australian",
            "Austrian",
            "Azerbaijani",
            "Bahamian",
            "Bahraini",
            "Bangladeshi",
            "Barbadian",
            "Barbudans",
            "Batswana",
            "Belarusian",
            "Belgian",
            "Belizean",
            "Beninese",
            "Bhutanese",
            "Bolivian",
            "Bosnian",
            "Brazilian",
            "British",
            "Bruneian",
            "Bulgarian",
            "Burkinabe",
            "Burmese",
            "Burundian",
            "Cambodian",
            "Cameroonian",
            "Canadian",
            "Cape Verdean",
            "Central African",
            "Chadian",
            "Chilean",
            "Chinese",
            "Colombian",
            "Comoran",
            "Congolese",
            "Costa Rican",
            "Croatian",
            "Cuban",
            "Cypriot",
            "Czech",
            "Danish",
            "Djibouti",
            "Dominican",
            "Dutch",
            "East Timorese",
            "Ecuadorean",
            "Egyptian",
            "Emirian",
            "Equatorial Guinean",
            "Eritrean",
            "Estonian",
            "Ethiopian",
            "Fijian",
            "Filipino",
            "Finnish",
            "French",
            "Gabonese",
            "Gambian",
            "Georgian",
            "German",
            "Ghanaian",
            "Greek",
            "Grenadian",
            "Guatemalan",
            "Guinea-Bissauan",
            "Guinean",
            "Guyanese",
            "Haitian",
            "Herzegovinian",
            "Honduran",
            "Hungarian",
            "I-Kiribati",
            "Icelander",
            "Indian",
            "Indonesian",
            "Iranian",
            "Iraqi",
            "Irish",
            "Israeli",
            "Italian",
            "Ivorian",
            "Jamaican",
            "Japanese",
            "Jordanian",
            "Kazakhstani",
            "Kenyan",
            "Kittian and Nevisian",
            "Kuwaiti",
            "Kyrgyz",
            "Laotian",
            "Latvian",
            "Lebanese",
            "Liberian",
            "Libyan",
            "Liechtensteiner",
            "Lithuanian",
            "Luxembourger",
            "Macedonian",
            "Malagasy",
            "Malawian",
            "Malaysian",
            "Maldivan",
            "Malian",
            "Maltese",
            "Marshallese",
            "Mauritanian",
            "Mauritian",
            "Mexican",
            "Micronesian",
            "Moldovan",
            "Monacan",
            "Mongolian",
            "Moroccan",
            "Mosotho",
            "Motswana",
            "Mozambican",
            "Namibian",
            "Nauruan",
            "Nepalese",
            "New Zealander",
            "Nicaraguan",
            "Nigerian",
            "Nigerien",
            "North Korean",
            "Northern Irish",
            "Norwegian",
            "Omani",
            "Pakistani",
            "Palauan",
            "Panamanian",
            "Papua New Guinean",
            "Paraguayan",
            "Peruvian",
            "Polish",
            "Portuguese",
            "Qatari",
            "Romanian",
            "Russian",
            "Rwandan",
            "Saint Lucian",
            "Salvadoran",
            "Samoan",
            "San Marinese",
            "Sao Tomean",
            "Saudi",
            "Scottish",
            "Senegalese",
            "Serbian",
            "Seychellois",
            "Sierra Leonean",
            "Singaporean",
            "Slovakian",
            "Slovenian",
            "Solomon Islander",
            "Somali",
            "South African",
            "South Korean",
            "Spanish",
            "Sri Lankan",
            "Sudanese",
            "Surinamer",
            "Swazi",
            "Swedish",
            "Swiss",
            "Syrian",
            "Taiwanese",
            "Tajik",
            "Tanzanian",
            "Thai",
            "Togolese",
            "Tongan",
            "Trinidadian or Tobagonian",
            "Tunisian",
            "Turkish",
            "Tuvaluan",
            "Ugandan",
            "Ukrainian",
            "Uruguayan",
            "Uzbekistani",
            "Venezuelan",
            "Vietnamese",
            "Welsh",
            "Yemenite",
            "Zambian",
            "Zimbabwean"
            ];

        $ar_nationalities = [
            "أفغاني",
            "الألبانية",
            "جزائري",
            "أمريكي",
            "أندورا",
            "الأنغولية",
            "أنتيجوان",
            "الأرجنتيني",
            "أرميني",
            "الاسترالية",
            "النمساوي",
            "أذربيجان",
            "جزر البهاما",
            "بحريني",
            "بنجلاديشية",
            "بربادوس",
            "باربودان",
            "باتسوانا",
            "البيلاروسية",
            "بلجيكي",
            "بليز",
            "بنين",
            "بوتاني",
            "بوليفي",
            "البوسنية",
            "برازيلي",
            "بريطاني",
            "بروناي",
            "البلغارية",
            "بوركينا فاسو",
            "البورمية",
            "بوروندي",
            "كمبودي",
            "الكاميروني",
            "كندي",
            "الرأس الأخضر",
            "أفريقيا الوسطى",
            "التشادية",
            "تشيلي",
            "صينى",
            "الكولومبي",
            "جزر القمر",
            "الكونغولية",
            "كوستاريكا",
            "الكرواتية",
            "الكوبي",
            "القبرصي",
            "التشيكية",
            "دانماركي",
            "جيبوتي",
            "الدومينيكان",
            "هولندي",
            "التيموريون الشرقيون",
            "الاكوادوري",
            "مصري",
            "أميركي",
            "غينيا الاستوائية",
            "اريتريا",
            "الإستونية",
            "الاثيوبية",
            "فيجي",
            "الفلبينية",
            "الفنلندية",
            "فرنسي",
            "الغابونية",
            "غامبي",
            "الجورجية",
            "ألمانية",
            "الغانية",
            "اليونانية",
            "غرينادا",
            "غواتيمالا",
            "غينيا بيساوان",
            "غينيا",
            "جوياني",
            "الهايتي",
            "هيرزيغوفينيان",
            "هندوراس",
            "المجرية",
            "آي كيريباتي",
            "آيسلندي",
            "هندي",
            "الأندونيسية",
            "إيراني",
            "عراقي",
            "إيرلندي",
            "إسرائيلي",
            "إيطالي",
            "ساحل العاج",
            "جامايكا",
            "اليابانية",
            "أردني",
            "الكازاخستانية",
            "كيني",
            "كيتيان ونيفيسيان",
            "كويتي",
            "قيرغيزستان",
            "اللاوسي",
            "لاتفيا",
            "لبناني",
            "الليبيرية",
            "ليبي",
            "ليختنشتاينر",
            "الليتوانية",
            "لوكسمبورج",
            "المقدونية",
            "مدغشقر",
            "مالاوي",
            "ماليزي",
            "مالديفان",
            "مالي",
            "المالطية",
            "مارشال",
            "موريتاني",
            "موريشيوس",
            "مكسيكي",
            "ميكرونيزي",
            "مولدوفا",
            "موناكان",
            "المنغولية",
            "مغربي",
            "موسوتو",
            "موتسوانا",
            "موزمبيقى",
            "الناميبي",
            "ناورو",
            "النيبالية",
            "نيوزيلندي",
            "نيكاراغوا",
            "نيجيري",
            "النيجر",
            "كوري شمالي",
            "شمالية إيرلندية",
            "النرويجية",
            "عماني",
            "باكستاني",
            "بالاوان",
            "بنمي",
            "بابوا غينيا الجديدة",
            "باراغواي",
            "بيرو",
            "تلميع",
            "البرتغالية",
            "قطري",
            "روماني",
            "الروسية",
            "رواندا",
            "سانت لوسيان",
            "السلفادورية",
            "ساموا",
            "سان مارينيزي",
            "ساو توميان",
            "سعودي",
            "اسكتلندي",
            "سنغالي",
            "الصربية",
            "سيشيل",
            "سيراليوني",
            "سنغافوري",
            "السلوفاكية",
            "السلوفينية",
            "جزر سليمان",
            "الصومالية",
            "جنوب افريقيا",
            "كوريا الجنوبية",
            "الأسبانية",
            "سري لانكا",
            "سوداني",
            "سورينامير",
            "سوازي",
            "السويدية",
            "سويسري",
            "سوري",
            "تايوانية",
            "طاجيك",
            "التنزانية",
            "التايلاندية",
            "التوغو",
            "تونغا",
            "ترينيدادية أو توباغونية",
            "تونسي",
            "اللغة التركية",
            "توفالوان",
            "أوغندا",
            "الأوكرانية",
            "أوروغواي",
            "أوزبكستان",
            "فنزويلية",
            "الفيتنامية",
            "ويلزي",
            "يمني",
            "زامبيا",
            "زمبابوي",
                ];

        $nationalities = [];

        foreach ($en_nationalities as $index => $name_en) {
            $nationalities[] = [
                'name_en' => $name_en,
                'name_ar' => $ar_nationalities[$index],
            ];
        }

        DB::table('nationalities')->insert($nationalities);
    }
}
